#ifndef  ENTITY_SDAISPECIFIED_HIGHER_USAGE_OCCURRENCE_H
#define  ENTITY_SDAISPECIFIED_HIGHER_USAGE_OCCURRENCE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSpecified_higher_usage_occurrence : public SdaiAssembly_component_usage {
     protected:
        SDAI_Application_instance_ptr _upper_usage;
        SDAI_Application_instance_ptr _next_usage;
    public: 
        SdaiSpecified_higher_usage_occurrence();
        SdaiSpecified_higher_usage_occurrence( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSpecified_higher_usage_occurrence( SdaiSpecified_higher_usage_occurrence & e );
        ~SdaiSpecified_higher_usage_occurrence();
        int opcode() {
            return 127;
        }
        SdaiAssembly_component_usage_ptr_c upper_usage_() const;
        SdaiAssembly_component_usage_ptr   upper_usage_();
        void upper_usage_( const SdaiAssembly_component_usage_ptr x );

        SdaiNext_assembly_usage_occurrence_ptr_c next_usage_() const;
        SdaiNext_assembly_usage_occurrence_ptr   next_usage_();
        void next_usage_( const SdaiNext_assembly_usage_occurrence_ptr x );

};

inline SdaiSpecified_higher_usage_occurrence * create_SdaiSpecified_higher_usage_occurrence() {
    return new SdaiSpecified_higher_usage_occurrence;
}

void init_SdaiSpecified_higher_usage_occurrence(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_specified_higher_usage_occurrence;
    extern AttrDescriptor *a_240upper_usage;
    extern AttrDescriptor *a_241next_usage;
}

#endif
