#ifndef  ENTITY_SDAISHELL_BASED_WIREFRAME_SHAPE_REPRESENTATION_H
#define  ENTITY_SDAISHELL_BASED_WIREFRAME_SHAPE_REPRESENTATION_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiShell_based_wireframe_shape_representation : public SdaiShape_representation {
     protected:
    public: 
        SdaiShell_based_wireframe_shape_representation();
        SdaiShell_based_wireframe_shape_representation( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiShell_based_wireframe_shape_representation( SdaiShell_based_wireframe_shape_representation & e );
        ~SdaiShell_based_wireframe_shape_representation();
        int opcode() {
            return 244;
        }
};

inline SdaiShell_based_wireframe_shape_representation * create_SdaiShell_based_wireframe_shape_representation() {
    return new SdaiShell_based_wireframe_shape_representation;
}

void init_SdaiShell_based_wireframe_shape_representation(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_shell_based_wireframe_shape_representation;
}

#endif
