#ifndef  ENTITY_SDAIAREA_MEASURE_WITH_UNIT_H
#define  ENTITY_SDAIAREA_MEASURE_WITH_UNIT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiArea_measure_with_unit : public SdaiMeasure_with_unit {
     protected:
    public: 
        SdaiArea_measure_with_unit();
        SdaiArea_measure_with_unit( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiArea_measure_with_unit( SdaiArea_measure_with_unit & e );
        ~SdaiArea_measure_with_unit();
        int opcode() {
            return 63;
        }
};

inline SdaiArea_measure_with_unit * create_SdaiArea_measure_with_unit() {
    return new SdaiArea_measure_with_unit;
}

void init_SdaiArea_measure_with_unit(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_area_measure_with_unit;
}

#endif
