#ifndef  ENTITY_SDAICHANGE_H
#define  ENTITY_SDAICHANGE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiChange : public SdaiAction_assignment {
     protected:
        SdaiWork_item_agg_ptr _items;          //  of  work_item

    public: 
        SdaiChange();
        SdaiChange( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiChange( SdaiChange & e );
        ~SdaiChange();
        int opcode() {
            return 171;
        }
        SdaiWork_item_agg_ptr_c items_() const;
        SdaiWork_item_agg_ptr   items_();
        void items_( const SdaiWork_item_agg_ptr x );

};

inline SdaiChange * create_SdaiChange() {
    return new SdaiChange;
}

void init_SdaiChange(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_change;
    extern AttrDescriptor *a_301items;
}

#endif
