#ifndef  ENTITY_SDAIFACETED_BREP_H
#define  ENTITY_SDAIFACETED_BREP_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiFaceted_brep : public SdaiManifold_solid_brep {
     protected:
    public: 
        SdaiFaceted_brep();
        SdaiFaceted_brep( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiFaceted_brep( SdaiFaceted_brep & e );
        ~SdaiFaceted_brep();
        int opcode() {
            return 28;
        }
};

inline SdaiFaceted_brep * create_SdaiFaceted_brep() {
    return new SdaiFaceted_brep;
}

void init_SdaiFaceted_brep(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_faceted_brep;
}

#endif
