#ifndef  ENTITY_SDAITOROIDAL_SURFACE_H
#define  ENTITY_SDAITOROIDAL_SURFACE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiToroidal_surface : public SdaiElementary_surface {
     protected:
        SDAI_Real _major_radius;
        SDAI_Real _minor_radius;
    public: 
        SdaiToroidal_surface();
        SdaiToroidal_surface( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiToroidal_surface( SdaiToroidal_surface & e );
        ~SdaiToroidal_surface();
        int opcode() {
            return 36;
        }
        SdaiPositive_length_measure   major_radius_() const;
        void major_radius_( const SdaiPositive_length_measure x );

        SdaiPositive_length_measure   minor_radius_() const;
        void minor_radius_( const SdaiPositive_length_measure x );

};

inline SdaiToroidal_surface * create_SdaiToroidal_surface() {
    return new SdaiToroidal_surface;
}

void init_SdaiToroidal_surface(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_toroidal_surface;
    extern AttrDescriptor *a_55major_radius;
    extern AttrDescriptor *a_56minor_radius;
}

#endif
