#ifndef  ENTITY_SDAIVERTEX_H
#define  ENTITY_SDAIVERTEX_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiVertex : public SdaiTopological_representation_item {
     protected:
    public: 
        SdaiVertex();
        SdaiVertex( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiVertex( SdaiVertex & e );
        ~SdaiVertex();
        int opcode() {
            return 139;
        }
};

inline SdaiVertex * create_SdaiVertex() {
    return new SdaiVertex;
}

void init_SdaiVertex(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_vertex;
}

#endif
