#ifndef  ENTITY_SDAIADVANCED_BREP_SHAPE_REPRESENTATION_H
#define  ENTITY_SDAIADVANCED_BREP_SHAPE_REPRESENTATION_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiAdvanced_brep_shape_representation : public SdaiShape_representation {
     protected:
    public: 
        SdaiAdvanced_brep_shape_representation();
        SdaiAdvanced_brep_shape_representation( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiAdvanced_brep_shape_representation( SdaiAdvanced_brep_shape_representation & e );
        ~SdaiAdvanced_brep_shape_representation();
        int opcode() {
            return 48;
        }
};

inline SdaiAdvanced_brep_shape_representation * create_SdaiAdvanced_brep_shape_representation() {
    return new SdaiAdvanced_brep_shape_representation;
}

void init_SdaiAdvanced_brep_shape_representation(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_advanced_brep_shape_representation;
}

#endif
