#ifndef  ENTITY_SDAICONNECTED_FACE_SET_H
#define  ENTITY_SDAICONNECTED_FACE_SET_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiConnected_face_set : public SdaiTopological_representation_item {
     protected:
        EntityAggregate_ptr _cfs_faces;          //  of  face

    public: 
        SdaiConnected_face_set();
        SdaiConnected_face_set( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiConnected_face_set( SdaiConnected_face_set & e );
        ~SdaiConnected_face_set();
        int opcode() {
            return 112;
        }
        EntityAggregate_ptr_c cfs_faces_() const;
        EntityAggregate_ptr   cfs_faces_();
        void cfs_faces_( const EntityAggregate_ptr x );

};

inline SdaiConnected_face_set * create_SdaiConnected_face_set() {
    return new SdaiConnected_face_set;
}

void init_SdaiConnected_face_set(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_connected_face_set;
    extern AttrDescriptor *a_216cfs_faces;
}

#endif
