#ifndef  ENTITY_SDAILINE_H
#define  ENTITY_SDAILINE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiLine : public SdaiCurve {
     protected:
        SDAI_Application_instance_ptr _pnt;
        SDAI_Application_instance_ptr _dir;
    public: 
        SdaiLine();
        SdaiLine( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiLine( SdaiLine & e );
        ~SdaiLine();
        int opcode() {
            return 173;
        }
        SdaiCartesian_point_ptr_c pnt_() const;
        SdaiCartesian_point_ptr   pnt_();
        void pnt_( const SdaiCartesian_point_ptr x );

        SdaiVector_ptr_c dir_() const;
        SdaiVector_ptr   dir_();
        void dir_( const SdaiVector_ptr x );

};

inline SdaiLine * create_SdaiLine() {
    return new SdaiLine;
}

void init_SdaiLine(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_line;
    extern AttrDescriptor *a_303pnt;
    extern AttrDescriptor *a_304dir;
}

#endif
