#ifndef  ENTITY_SDAIBOUNDED_CURVE_H
#define  ENTITY_SDAIBOUNDED_CURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiBounded_curve : public SdaiCurve {
     protected:
    public: 
        SdaiBounded_curve();
        SdaiBounded_curve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiBounded_curve( SdaiBounded_curve & e );
        ~SdaiBounded_curve();
        int opcode() {
            return 12;
        }
};

inline SdaiBounded_curve * create_SdaiBounded_curve() {
    return new SdaiBounded_curve;
}

void init_SdaiBounded_curve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_bounded_curve;
}

#endif
