#ifndef  ENTITY_SDAIGLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT_H
#define  ENTITY_SDAIGLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiGlobal_uncertainty_assigned_context : public SdaiRepresentation_context {
     protected:
        EntityAggregate_ptr _uncertainty;          //  of  uncertainty_measure_with_unit

    public: 
        SdaiGlobal_uncertainty_assigned_context();
        SdaiGlobal_uncertainty_assigned_context( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiGlobal_uncertainty_assigned_context( SdaiGlobal_uncertainty_assigned_context & e );
        ~SdaiGlobal_uncertainty_assigned_context();
        int opcode() {
            return 145;
        }
        EntityAggregate_ptr_c uncertainty_() const;
        EntityAggregate_ptr   uncertainty_();
        void uncertainty_( const EntityAggregate_ptr x );

};

inline SdaiGlobal_uncertainty_assigned_context * create_SdaiGlobal_uncertainty_assigned_context() {
    return new SdaiGlobal_uncertainty_assigned_context;
}

void init_SdaiGlobal_uncertainty_assigned_context(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_global_uncertainty_assigned_context;
    extern AttrDescriptor *a_270uncertainty;
}

#endif
