#ifndef  ENTITY_SDAIBREP_WITH_VOIDS_H
#define  ENTITY_SDAIBREP_WITH_VOIDS_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiBrep_with_voids : public SdaiManifold_solid_brep {
     protected:
        EntityAggregate_ptr _voids;          //  of  oriented_closed_shell

    public: 
        SdaiBrep_with_voids();
        SdaiBrep_with_voids( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiBrep_with_voids( SdaiBrep_with_voids & e );
        ~SdaiBrep_with_voids();
        int opcode() {
            return 231;
        }
        EntityAggregate_ptr_c voids_() const;
        EntityAggregate_ptr   voids_();
        void voids_( const EntityAggregate_ptr x );

};

inline SdaiBrep_with_voids * create_SdaiBrep_with_voids() {
    return new SdaiBrep_with_voids;
}

void init_SdaiBrep_with_voids(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_brep_with_voids;
    extern AttrDescriptor *a_401voids;
}

#endif
