#ifndef  ENTITY_SDAIMASS_UNIT_H
#define  ENTITY_SDAIMASS_UNIT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiMass_unit : public SdaiNamed_unit {
     protected:
    public: 
        SdaiMass_unit();
        SdaiMass_unit( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiMass_unit( SdaiMass_unit & e );
        ~SdaiMass_unit();
        int opcode() {
            return 30;
        }
};

inline SdaiMass_unit * create_SdaiMass_unit() {
    return new SdaiMass_unit;
}

void init_SdaiMass_unit(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_mass_unit;
}

#endif
