#ifndef  ENTITY_SDAISPHERICAL_SURFACE_H
#define  ENTITY_SDAISPHERICAL_SURFACE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSpherical_surface : public SdaiElementary_surface {
     protected:
        SDAI_Real _radius;
    public: 
        SdaiSpherical_surface();
        SdaiSpherical_surface( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSpherical_surface( SdaiSpherical_surface & e );
        ~SdaiSpherical_surface();
        int opcode() {
            return 102;
        }
        SdaiPositive_length_measure   radius_() const;
        void radius_( const SdaiPositive_length_measure x );

};

inline SdaiSpherical_surface * create_SdaiSpherical_surface() {
    return new SdaiSpherical_surface;
}

void init_SdaiSpherical_surface(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_spherical_surface;
    extern AttrDescriptor *a_200radius;
}

#endif
