#ifndef  ENTITY_SDAICERTIFICATION_TYPE_H
#define  ENTITY_SDAICERTIFICATION_TYPE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiCertification_type : public SDAI_Application_instance {
    protected:
        SDAI_String _description;
    public: 
        SdaiCertification_type();
        SdaiCertification_type( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiCertification_type( SdaiCertification_type & e );
        ~SdaiCertification_type();
        int opcode() {
            return 236;
        }
  const SdaiLabel   description_() const;
        SdaiLabel   description_();
        void description_( const SdaiLabel x );

};

inline SdaiCertification_type * create_SdaiCertification_type() {
    return new SdaiCertification_type;
}

void init_SdaiCertification_type(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_certification_type;
    extern AttrDescriptor *a_412description;
}

#endif
