#ifndef  ENTITY_SDAICC_DESIGN_DATE_AND_TIME_ASSIGNMENT_H
#define  ENTITY_SDAICC_DESIGN_DATE_AND_TIME_ASSIGNMENT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiCc_design_date_and_time_assignment : public SdaiDate_and_time_assignment {
     protected:
        SdaiDate_time_item_agg_ptr _items;          //  of  date_time_item

    public: 
        SdaiCc_design_date_and_time_assignment();
        SdaiCc_design_date_and_time_assignment( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiCc_design_date_and_time_assignment( SdaiCc_design_date_and_time_assignment & e );
        ~SdaiCc_design_date_and_time_assignment();
        int opcode() {
            return 76;
        }
        SdaiDate_time_item_agg_ptr_c items_() const;
        SdaiDate_time_item_agg_ptr   items_();
        void items_( const SdaiDate_time_item_agg_ptr x );

};

inline SdaiCc_design_date_and_time_assignment * create_SdaiCc_design_date_and_time_assignment() {
    return new SdaiCc_design_date_and_time_assignment;
}

void init_SdaiCc_design_date_and_time_assignment(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_cc_design_date_and_time_assignment;
    extern AttrDescriptor *a_157items;
}

#endif
