#ifndef  ENTITY_SDAISECURITY_CLASSIFICATION_ASSIGNMENT_H
#define  ENTITY_SDAISECURITY_CLASSIFICATION_ASSIGNMENT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSecurity_classification_assignment : public SDAI_Application_instance {
    protected:
        SDAI_Application_instance_ptr _assigned_security_classification;
    public: 
        SdaiSecurity_classification_assignment();
        SdaiSecurity_classification_assignment( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSecurity_classification_assignment( SdaiSecurity_classification_assignment & e );
        ~SdaiSecurity_classification_assignment();
        int opcode() {
            return 153;
        }
        SdaiSecurity_classification_ptr_c assigned_security_classification_() const;
        SdaiSecurity_classification_ptr   assigned_security_classification_();
        void assigned_security_classification_( const SdaiSecurity_classification_ptr x );

};

inline SdaiSecurity_classification_assignment * create_SdaiSecurity_classification_assignment() {
    return new SdaiSecurity_classification_assignment;
}

void init_SdaiSecurity_classification_assignment(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_security_classification_assignment;
    extern AttrDescriptor *a_278assigned_security_classification;
}

#endif
