#ifndef  ENTITY_SDAICONTRACT_ASSIGNMENT_H
#define  ENTITY_SDAICONTRACT_ASSIGNMENT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiContract_assignment : public SDAI_Application_instance {
    protected:
        SDAI_Application_instance_ptr _assigned_contract;
    public: 
        SdaiContract_assignment();
        SdaiContract_assignment( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiContract_assignment( SdaiContract_assignment & e );
        ~SdaiContract_assignment();
        int opcode() {
            return 103;
        }
        SdaiContract_ptr_c assigned_contract_() const;
        SdaiContract_ptr   assigned_contract_();
        void assigned_contract_( const SdaiContract_ptr x );

};

inline SdaiContract_assignment * create_SdaiContract_assignment() {
    return new SdaiContract_assignment;
}

void init_SdaiContract_assignment(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_contract_assignment;
    extern AttrDescriptor *a_201assigned_contract;
}

#endif
