#ifndef  ENTITY_SDAIEDGE_CURVE_H
#define  ENTITY_SDAIEDGE_CURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiEdge_curve : public SdaiEdge {
     protected:
        SDAI_Application_instance_ptr _edge_geometry;
        SDAI_BOOLEAN _same_sense;
    public: 
        SdaiEdge_curve();
        SdaiEdge_curve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiEdge_curve( SdaiEdge_curve & e );
        ~SdaiEdge_curve();
        int opcode() {
            return 250;
        }
        SdaiCurve_ptr_c edge_geometry_() const;
        SdaiCurve_ptr   edge_geometry_();
        void edge_geometry_( const SdaiCurve_ptr x );

        Boolean   same_sense_() const;
        void same_sense_( const Boolean x );

};

inline SdaiEdge_curve * create_SdaiEdge_curve() {
    return new SdaiEdge_curve;
}

void init_SdaiEdge_curve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_edge_curve;
    extern AttrDescriptor *a_433edge_geometry;
    extern AttrDescriptor *a_434same_sense;
}

#endif
