#ifndef  ENTITY_SDAIDEGENERATE_PCURVE_H
#define  ENTITY_SDAIDEGENERATE_PCURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiDegenerate_pcurve : public SdaiPoint {
     protected:
        SDAI_Application_instance_ptr _basis_surface;
        SDAI_Application_instance_ptr _reference_to_curve;
    public: 
        SdaiDegenerate_pcurve();
        SdaiDegenerate_pcurve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiDegenerate_pcurve( SdaiDegenerate_pcurve & e );
        ~SdaiDegenerate_pcurve();
        int opcode() {
            return 74;
        }
        SdaiSurface_ptr_c basis_surface_() const;
        SdaiSurface_ptr   basis_surface_();
        void basis_surface_( const SdaiSurface_ptr x );

        SdaiDefinitional_representation_ptr_c reference_to_curve_() const;
        SdaiDefinitional_representation_ptr   reference_to_curve_();
        void reference_to_curve_( const SdaiDefinitional_representation_ptr x );

};

inline SdaiDegenerate_pcurve * create_SdaiDegenerate_pcurve() {
    return new SdaiDegenerate_pcurve;
}

void init_SdaiDegenerate_pcurve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_degenerate_pcurve;
    extern AttrDescriptor *a_153basis_surface;
    extern AttrDescriptor *a_154reference_to_curve;
}

#endif
