#ifndef  ENTITY_SDAIPRODUCT_CONTEXT_H
#define  ENTITY_SDAIPRODUCT_CONTEXT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiProduct_context : public SdaiApplication_context_element {
     protected:
        SDAI_String _discipline_type;
    public: 
        SdaiProduct_context();
        SdaiProduct_context( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiProduct_context( SdaiProduct_context & e );
        ~SdaiProduct_context();
        int opcode() {
            return 202;
        }
  const SdaiLabel   discipline_type_() const;
        SdaiLabel   discipline_type_();
        void discipline_type_( const SdaiLabel x );

};

inline SdaiProduct_context * create_SdaiProduct_context() {
    return new SdaiProduct_context;
}

void init_SdaiProduct_context(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_product_context;
    extern AttrDescriptor *a_360discipline_type;
}

#endif
