#ifndef  ENTITY_SDAIREPRESENTATION_MAP_H
#define  ENTITY_SDAIREPRESENTATION_MAP_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRepresentation_map : public SDAI_Application_instance {
    protected:
        SDAI_Application_instance_ptr _mapping_origin;
        SDAI_Application_instance_ptr _mapped_representation;
    public: 
        SdaiRepresentation_map();
        SdaiRepresentation_map( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRepresentation_map( SdaiRepresentation_map & e );
        ~SdaiRepresentation_map();
        int opcode() {
            return 225;
        }
        SdaiRepresentation_item_ptr_c mapping_origin_() const;
        SdaiRepresentation_item_ptr   mapping_origin_();
        void mapping_origin_( const SdaiRepresentation_item_ptr x );

        SdaiRepresentation_ptr_c mapped_representation_() const;
        SdaiRepresentation_ptr   mapped_representation_();
        void mapped_representation_( const SdaiRepresentation_ptr x );

        EntityAggregate_ptr_c map_usage_() const;
        EntityAggregate_ptr   map_usage_();
        void map_usage_( const EntityAggregate_ptr x );

};

inline SdaiRepresentation_map * create_SdaiRepresentation_map() {
    return new SdaiRepresentation_map;
}

void init_SdaiRepresentation_map(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_representation_map;
    extern AttrDescriptor *a_393mapping_origin;
    extern AttrDescriptor *a_394mapped_representation;
    extern Inverse_attribute *a_395Imap_usage;
}

#endif
