#ifndef  ENTITY_SDAIAPPROVAL_STATUS_H
#define  ENTITY_SDAIAPPROVAL_STATUS_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiApproval_status : public SDAI_Application_instance {
    protected:
        SDAI_String _name;
    public: 
        SdaiApproval_status();
        SdaiApproval_status( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiApproval_status( SdaiApproval_status & e );
        ~SdaiApproval_status();
        int opcode() {
            return 223;
        }
  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

};

inline SdaiApproval_status * create_SdaiApproval_status() {
    return new SdaiApproval_status;
}

void init_SdaiApproval_status(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_approval_status;
    extern AttrDescriptor *a_389name;
}

#endif
