#ifndef  ENTITY_SDAISUPPLIED_PART_RELATIONSHIP_H
#define  ENTITY_SDAISUPPLIED_PART_RELATIONSHIP_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSupplied_part_relationship : public SdaiProduct_definition_relationship {
     protected:
    public: 
        SdaiSupplied_part_relationship();
        SdaiSupplied_part_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSupplied_part_relationship( SdaiSupplied_part_relationship & e );
        ~SdaiSupplied_part_relationship();
        int opcode() {
            return 248;
        }
};

inline SdaiSupplied_part_relationship * create_SdaiSupplied_part_relationship() {
    return new SdaiSupplied_part_relationship;
}

void init_SdaiSupplied_part_relationship(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_supplied_part_relationship;
}

#endif
