#ifndef  ENTITY_SDAIORGANIZATION_RELATIONSHIP_H
#define  ENTITY_SDAIORGANIZATION_RELATIONSHIP_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiOrganization_relationship : public SDAI_Application_instance {
    protected:
        SDAI_String _name;
        SDAI_String _description;
        SDAI_Application_instance_ptr _relating_organization;
        SDAI_Application_instance_ptr _related_organization;
    public: 
        SdaiOrganization_relationship();
        SdaiOrganization_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiOrganization_relationship( SdaiOrganization_relationship & e );
        ~SdaiOrganization_relationship();
        int opcode() {
            return 39;
        }
  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

        SdaiOrganization_ptr_c relating_organization_() const;
        SdaiOrganization_ptr   relating_organization_();
        void relating_organization_( const SdaiOrganization_ptr x );

        SdaiOrganization_ptr_c related_organization_() const;
        SdaiOrganization_ptr   related_organization_();
        void related_organization_( const SdaiOrganization_ptr x );

};

inline SdaiOrganization_relationship * create_SdaiOrganization_relationship() {
    return new SdaiOrganization_relationship;
}

void init_SdaiOrganization_relationship(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_organization_relationship;
    extern AttrDescriptor *a_60name;
    extern AttrDescriptor *a_61description;
    extern AttrDescriptor *a_62relating_organization;
    extern AttrDescriptor *a_63related_organization;
}

#endif
