#ifndef  ENTITY_SDAIMAPPED_ITEM_H
#define  ENTITY_SDAIMAPPED_ITEM_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiMapped_item : public SdaiRepresentation_item {
     protected:
        SDAI_Application_instance_ptr _mapping_source;
        SDAI_Application_instance_ptr _mapping_target;
    public: 
        SdaiMapped_item();
        SdaiMapped_item( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiMapped_item( SdaiMapped_item & e );
        ~SdaiMapped_item();
        int opcode() {
            return 128;
        }
        SdaiRepresentation_map_ptr_c mapping_source_() const;
        SdaiRepresentation_map_ptr   mapping_source_();
        void mapping_source_( const SdaiRepresentation_map_ptr x );

        SdaiRepresentation_item_ptr_c mapping_target_() const;
        SdaiRepresentation_item_ptr   mapping_target_();
        void mapping_target_( const SdaiRepresentation_item_ptr x );

};

inline SdaiMapped_item * create_SdaiMapped_item() {
    return new SdaiMapped_item;
}

void init_SdaiMapped_item(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_mapped_item;
    extern AttrDescriptor *a_242mapping_source;
    extern AttrDescriptor *a_243mapping_target;
}

#endif
