#ifndef  ENTITY_SDAIFACE_H
#define  ENTITY_SDAIFACE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiFace : public SdaiTopological_representation_item {
     protected:
        EntityAggregate_ptr _bounds;          //  of  face_bound

    public: 
        SdaiFace();
        SdaiFace( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiFace( SdaiFace & e );
        ~SdaiFace();
        int opcode() {
            return 50;
        }
        EntityAggregate_ptr_c bounds_() const;
        EntityAggregate_ptr   bounds_();
        void bounds_( const EntityAggregate_ptr x );

};

inline SdaiFace * create_SdaiFace() {
    return new SdaiFace;
}

void init_SdaiFace(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_face;
    extern AttrDescriptor *a_96bounds;
}

#endif
