#ifndef  ENTITY_SDAICONICAL_SURFACE_H
#define  ENTITY_SDAICONICAL_SURFACE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiConical_surface : public SdaiElementary_surface {
     protected:
        SDAI_Real _radius;
        SDAI_Real _semi_angle;
    public: 
        SdaiConical_surface();
        SdaiConical_surface( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiConical_surface( SdaiConical_surface & e );
        ~SdaiConical_surface();
        int opcode() {
            return 249;
        }
        SdaiLength_measure   radius_() const;
        void radius_( const SdaiLength_measure x );

        SdaiPlane_angle_measure   semi_angle_() const;
        void semi_angle_( const SdaiPlane_angle_measure x );

};

inline SdaiConical_surface * create_SdaiConical_surface() {
    return new SdaiConical_surface;
}

void init_SdaiConical_surface(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_conical_surface;
    extern AttrDescriptor *a_431radius;
    extern AttrDescriptor *a_432semi_angle;
}

#endif
