#ifndef  ENTITY_SDAIDIRECTION_H
#define  ENTITY_SDAIDIRECTION_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiDirection : public SdaiGeometric_representation_item {
     protected:
        RealAggregate_ptr _direction_ratios;
    public: 
        SdaiDirection();
        SdaiDirection( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiDirection( SdaiDirection & e );
        ~SdaiDirection();
        int opcode() {
            return 222;
        }
        RealAggregate_ptr_c direction_ratios_() const;
        RealAggregate_ptr   direction_ratios_();
        void direction_ratios_( const RealAggregate_ptr x );

};

inline SdaiDirection * create_SdaiDirection() {
    return new SdaiDirection;
}

void init_SdaiDirection(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_direction;
    extern AttrDescriptor *a_388direction_ratios;
}

#endif
