#ifndef  ENTITY_SDAISOLID_MODEL_H
#define  ENTITY_SDAISOLID_MODEL_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSolid_model : public SdaiGeometric_representation_item {
     protected:
    public: 
        SdaiSolid_model();
        SdaiSolid_model( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSolid_model( SdaiSolid_model & e );
        ~SdaiSolid_model();
        int opcode() {
            return 26;
        }
};

inline SdaiSolid_model * create_SdaiSolid_model() {
    return new SdaiSolid_model;
}

void init_SdaiSolid_model(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_solid_model;
}

#endif
