#ifndef  ENTITY_SDAIPOINT_REPLICA_H
#define  ENTITY_SDAIPOINT_REPLICA_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiPoint_replica : public SdaiPoint {
     protected:
        SDAI_Application_instance_ptr _parent_pt;
        SDAI_Application_instance_ptr _transformation;
    public: 
        SdaiPoint_replica();
        SdaiPoint_replica( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiPoint_replica( SdaiPoint_replica & e );
        ~SdaiPoint_replica();
        int opcode() {
            return 219;
        }
        SdaiPoint_ptr_c parent_pt_() const;
        SdaiPoint_ptr   parent_pt_();
        void parent_pt_( const SdaiPoint_ptr x );

        SdaiCartesian_transformation_operator_ptr_c transformation_() const;
        SdaiCartesian_transformation_operator_ptr   transformation_();
        void transformation_( const SdaiCartesian_transformation_operator_ptr x );

};

inline SdaiPoint_replica * create_SdaiPoint_replica() {
    return new SdaiPoint_replica;
}

void init_SdaiPoint_replica(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_point_replica;
    extern AttrDescriptor *a_382parent_pt;
    extern AttrDescriptor *a_383transformation;
}

#endif
