#ifndef  ENTITY_SDAIUNIFORM_SURFACE_H
#define  ENTITY_SDAIUNIFORM_SURFACE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiUniform_surface : public SdaiB_spline_surface {
     protected:
    public: 
        SdaiUniform_surface();
        SdaiUniform_surface( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiUniform_surface( SdaiUniform_surface & e );
        ~SdaiUniform_surface();
        int opcode() {
            return 79;
        }
};

inline SdaiUniform_surface * create_SdaiUniform_surface() {
    return new SdaiUniform_surface;
}

void init_SdaiUniform_surface(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_uniform_surface;
}

#endif
