#ifndef  ENTITY_SDAIPOINT_ON_CURVE_H
#define  ENTITY_SDAIPOINT_ON_CURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiPoint_on_curve : public SdaiPoint {
     protected:
        SDAI_Application_instance_ptr _basis_curve;
        SDAI_Real _point_parameter;
    public: 
        SdaiPoint_on_curve();
        SdaiPoint_on_curve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiPoint_on_curve( SdaiPoint_on_curve & e );
        ~SdaiPoint_on_curve();
        int opcode() {
            return 238;
        }
        SdaiCurve_ptr_c basis_curve_() const;
        SdaiCurve_ptr   basis_curve_();
        void basis_curve_( const SdaiCurve_ptr x );

        SdaiParameter_value   point_parameter_() const;
        void point_parameter_( const SdaiParameter_value x );

};

inline SdaiPoint_on_curve * create_SdaiPoint_on_curve() {
    return new SdaiPoint_on_curve;
}

void init_SdaiPoint_on_curve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_point_on_curve;
    extern AttrDescriptor *a_415basis_curve;
    extern AttrDescriptor *a_416point_parameter;
}

#endif
