#ifndef  ENTITY_SDAILOOP_H
#define  ENTITY_SDAILOOP_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiLoop : public SdaiTopological_representation_item {
     protected:
    public: 
        SdaiLoop();
        SdaiLoop( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiLoop( SdaiLoop & e );
        ~SdaiLoop();
        int opcode() {
            return 94;
        }
};

inline SdaiLoop * create_SdaiLoop() {
    return new SdaiLoop;
}

void init_SdaiLoop(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_loop;
}

#endif
