#ifndef  ENTITY_SDAISURFACE_REPLICA_H
#define  ENTITY_SDAISURFACE_REPLICA_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSurface_replica : public SdaiSurface {
     protected:
        SDAI_Application_instance_ptr _parent_surface;
        SDAI_Application_instance_ptr _transformation;
    public: 
        SdaiSurface_replica();
        SdaiSurface_replica( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSurface_replica( SdaiSurface_replica & e );
        ~SdaiSurface_replica();
        int opcode() {
            return 21;
        }
        SdaiSurface_ptr_c parent_surface_() const;
        SdaiSurface_ptr   parent_surface_();
        void parent_surface_( const SdaiSurface_ptr x );

        SdaiCartesian_transformation_operator_3d_ptr_c transformation_() const;
        SdaiCartesian_transformation_operator_3d_ptr   transformation_();
        void transformation_( const SdaiCartesian_transformation_operator_3d_ptr x );

};

inline SdaiSurface_replica * create_SdaiSurface_replica() {
    return new SdaiSurface_replica;
}

void init_SdaiSurface_replica(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_surface_replica;
    extern AttrDescriptor *a_33parent_surface;
    extern AttrDescriptor *a_34transformation;
}

#endif
