#ifndef  ENTITY_SDAICALENDAR_DATE_H
#define  ENTITY_SDAICALENDAR_DATE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiCalendar_date : public SdaiDate {
     protected:
        SDAI_Integer _day_component;
        SDAI_Integer _month_component;
    public: 
        SdaiCalendar_date();
        SdaiCalendar_date( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiCalendar_date( SdaiCalendar_date & e );
        ~SdaiCalendar_date();
        int opcode() {
            return 157;
        }
        SdaiDay_in_month_number   day_component_() const;
        void day_component_( const SdaiDay_in_month_number x );

        SdaiMonth_in_year_number   month_component_() const;
        void month_component_( const SdaiMonth_in_year_number x );

};

inline SdaiCalendar_date * create_SdaiCalendar_date() {
    return new SdaiCalendar_date;
}

void init_SdaiCalendar_date(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_calendar_date;
    extern AttrDescriptor *a_283day_component;
    extern AttrDescriptor *a_284month_component;
}

#endif
