#ifndef  ENTITY_SDAIORGANIZATIONAL_PROJECT_H
#define  ENTITY_SDAIORGANIZATIONAL_PROJECT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiOrganizational_project : public SDAI_Application_instance {
    protected:
        SDAI_String _name;
        SDAI_String _description;
        EntityAggregate_ptr _responsible_organizations;          //  of  organization

    public: 
        SdaiOrganizational_project();
        SdaiOrganizational_project( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiOrganizational_project( SdaiOrganizational_project & e );
        ~SdaiOrganizational_project();
        int opcode() {
            return 181;
        }
  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

        EntityAggregate_ptr_c responsible_organizations_() const;
        EntityAggregate_ptr   responsible_organizations_();
        void responsible_organizations_( const EntityAggregate_ptr x );

};

inline SdaiOrganizational_project * create_SdaiOrganizational_project() {
    return new SdaiOrganizational_project;
}

void init_SdaiOrganizational_project(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_organizational_project;
    extern AttrDescriptor *a_322name;
    extern AttrDescriptor *a_323description;
    extern AttrDescriptor *a_324responsible_organizations;
}

#endif
