#ifndef  ENTITY_SDAIAPPROVAL_H
#define  ENTITY_SDAIAPPROVAL_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiApproval : public SDAI_Application_instance {
    protected:
        SDAI_Application_instance_ptr _status;
        SDAI_String _level;
    public: 
        SdaiApproval();
        SdaiApproval( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiApproval( SdaiApproval & e );
        ~SdaiApproval();
        int opcode() {
            return 93;
        }
        SdaiApproval_status_ptr_c status_() const;
        SdaiApproval_status_ptr   status_();
        void status_( const SdaiApproval_status_ptr x );

  const SdaiLabel   level_() const;
        SdaiLabel   level_();
        void level_( const SdaiLabel x );

};

inline SdaiApproval * create_SdaiApproval() {
    return new SdaiApproval;
}

void init_SdaiApproval(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_approval;
    extern AttrDescriptor *a_186status;
    extern AttrDescriptor *a_187level;
}

#endif
