#ifndef  ENTITY_SDAIELEMENTARY_SURFACE_H
#define  ENTITY_SDAIELEMENTARY_SURFACE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiElementary_surface : public SdaiSurface {
     protected:
        SDAI_Application_instance_ptr _position;
    public: 
        SdaiElementary_surface();
        SdaiElementary_surface( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiElementary_surface( SdaiElementary_surface & e );
        ~SdaiElementary_surface();
        int opcode() {
            return 35;
        }
        SdaiAxis2_placement_3d_ptr_c position_() const;
        SdaiAxis2_placement_3d_ptr   position_();
        void position_( const SdaiAxis2_placement_3d_ptr x );

};

inline SdaiElementary_surface * create_SdaiElementary_surface() {
    return new SdaiElementary_surface;
}

void init_SdaiElementary_surface(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_elementary_surface;
    extern AttrDescriptor *a_54position;
}

#endif
