#ifndef  ENTITY_SDAIEVALUATED_DEGENERATE_PCURVE_H
#define  ENTITY_SDAIEVALUATED_DEGENERATE_PCURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiEvaluated_degenerate_pcurve : public SdaiDegenerate_pcurve {
     protected:
        SDAI_Application_instance_ptr _equivalent_point;
    public: 
        SdaiEvaluated_degenerate_pcurve();
        SdaiEvaluated_degenerate_pcurve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiEvaluated_degenerate_pcurve( SdaiEvaluated_degenerate_pcurve & e );
        ~SdaiEvaluated_degenerate_pcurve();
        int opcode() {
            return 146;
        }
        SdaiCartesian_point_ptr_c equivalent_point_() const;
        SdaiCartesian_point_ptr   equivalent_point_();
        void equivalent_point_( const SdaiCartesian_point_ptr x );

};

inline SdaiEvaluated_degenerate_pcurve * create_SdaiEvaluated_degenerate_pcurve() {
    return new SdaiEvaluated_degenerate_pcurve;
}

void init_SdaiEvaluated_degenerate_pcurve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_evaluated_degenerate_pcurve;
    extern AttrDescriptor *a_271equivalent_point;
}

#endif
