#ifndef  ENTITY_SDAIBOUNDED_PCURVE_H
#define  ENTITY_SDAIBOUNDED_PCURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiBounded_pcurve : public SdaiPcurve {
     protected:
    public: 
        SdaiBounded_pcurve();
        SdaiBounded_pcurve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiBounded_pcurve( SdaiBounded_pcurve & e );
        ~SdaiBounded_pcurve();
        int opcode() {
            return 167;
        }
};

inline SdaiBounded_pcurve * create_SdaiBounded_pcurve() {
    return new SdaiBounded_pcurve;
}

void init_SdaiBounded_pcurve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_bounded_pcurve;
}

#endif
