#ifndef  ENTITY_SDAISTART_REQUEST_H
#define  ENTITY_SDAISTART_REQUEST_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiStart_request : public SdaiAction_request_assignment {
     protected:
        SdaiStart_request_item_agg_ptr _items;          //  of  start_request_item

    public: 
        SdaiStart_request();
        SdaiStart_request( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiStart_request( SdaiStart_request & e );
        ~SdaiStart_request();
        int opcode() {
            return 99;
        }
        SdaiStart_request_item_agg_ptr_c items_() const;
        SdaiStart_request_item_agg_ptr   items_();
        void items_( const SdaiStart_request_item_agg_ptr x );

};

inline SdaiStart_request * create_SdaiStart_request() {
    return new SdaiStart_request;
}

void init_SdaiStart_request(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_start_request;
    extern AttrDescriptor *a_198items;
}

#endif
