#ifndef  ENTITY_SDAISHAPE_DEFINITION_REPRESENTATION_H
#define  ENTITY_SDAISHAPE_DEFINITION_REPRESENTATION_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiShape_definition_representation : public SdaiProperty_definition_representation {
     protected:
    public: 
        SdaiShape_definition_representation();
        SdaiShape_definition_representation( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiShape_definition_representation( SdaiShape_definition_representation & e );
        ~SdaiShape_definition_representation();
        int opcode() {
            return 111;
        }
};

inline SdaiShape_definition_representation * create_SdaiShape_definition_representation() {
    return new SdaiShape_definition_representation;
}

void init_SdaiShape_definition_representation(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_shape_definition_representation;
}

#endif
