#ifndef  ENTITY_SDAIPATH_H
#define  ENTITY_SDAIPATH_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiPath : public SdaiTopological_representation_item {
     protected:
        EntityAggregate_ptr _edge_list;          //  of  oriented_edge

    public: 
        SdaiPath();
        SdaiPath( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiPath( SdaiPath & e );
        ~SdaiPath();
        int opcode() {
            return 90;
        }
        EntityAggregate_ptr_c edge_list_() const;
        EntityAggregate_ptr   edge_list_();
        void edge_list_( const EntityAggregate_ptr x );

};

inline SdaiPath * create_SdaiPath() {
    return new SdaiPath;
}

void init_SdaiPath(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_path;
    extern AttrDescriptor *a_183edge_list;
}

#endif
