#ifndef  ENTITY_SDAIPOINT_H
#define  ENTITY_SDAIPOINT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiPoint : public SdaiGeometric_representation_item {
     protected:
    public: 
        SdaiPoint();
        SdaiPoint( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiPoint( SdaiPoint & e );
        ~SdaiPoint();
        int opcode() {
            return 73;
        }
};

inline SdaiPoint * create_SdaiPoint() {
    return new SdaiPoint;
}

void init_SdaiPoint(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_point;
}

#endif
