#ifndef  ENTITY_SDAIRATIONAL_B_SPLINE_CURVE_H
#define  ENTITY_SDAIRATIONAL_B_SPLINE_CURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRational_b_spline_curve : public SdaiB_spline_curve {
     protected:
        RealAggregate_ptr _weights_data;
    public: 
        SdaiRational_b_spline_curve();
        SdaiRational_b_spline_curve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRational_b_spline_curve( SdaiRational_b_spline_curve & e );
        ~SdaiRational_b_spline_curve();
        int opcode() {
            return 98;
        }
        RealAggregate_ptr_c weights_data_() const;
        RealAggregate_ptr   weights_data_();
        void weights_data_( const RealAggregate_ptr x );

};

inline SdaiRational_b_spline_curve * create_SdaiRational_b_spline_curve() {
    return new SdaiRational_b_spline_curve;
}

void init_SdaiRational_b_spline_curve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_rational_b_spline_curve;
    extern AttrDescriptor *a_196weights_data;
    extern Derived_attribute *a_197Dweights;
}

#endif
