#ifndef  ENTITY_SDAINAMED_UNIT_H
#define  ENTITY_SDAINAMED_UNIT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiNamed_unit : public SDAI_Application_instance {
    protected:
        SDAI_Application_instance_ptr _dimensions;
    public: 
        SdaiNamed_unit();
        SdaiNamed_unit( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiNamed_unit( SdaiNamed_unit & e );
        ~SdaiNamed_unit();
        int opcode() {
            return 29;
        }
        SdaiDimensional_exponents_ptr_c dimensions_() const;
        SdaiDimensional_exponents_ptr   dimensions_();
        void dimensions_( const SdaiDimensional_exponents_ptr x );

};

inline SdaiNamed_unit * create_SdaiNamed_unit() {
    return new SdaiNamed_unit;
}

void init_SdaiNamed_unit(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_named_unit;
    extern AttrDescriptor *a_49dimensions;
}

#endif
