#ifndef  ENTITY_SDAICONTEXT_DEPENDENT_UNIT_H
#define  ENTITY_SDAICONTEXT_DEPENDENT_UNIT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiContext_dependent_unit : public SdaiNamed_unit {
     protected:
        SDAI_String _name;
    public: 
        SdaiContext_dependent_unit();
        SdaiContext_dependent_unit( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiContext_dependent_unit( SdaiContext_dependent_unit & e );
        ~SdaiContext_dependent_unit();
        int opcode() {
            return 121;
        }
  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

};

inline SdaiContext_dependent_unit * create_SdaiContext_dependent_unit() {
    return new SdaiContext_dependent_unit;
}

void init_SdaiContext_dependent_unit(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_context_dependent_unit;
    extern AttrDescriptor *a_230name;
}

#endif
