#ifndef  ENTITY_SDAIAXIS2_PLACEMENT_3D_H
#define  ENTITY_SDAIAXIS2_PLACEMENT_3D_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiAxis2_placement_3d : public SdaiPlacement {
     protected:
        SDAI_Application_instance_ptr _axis;    //  OPTIONAL
        SDAI_Application_instance_ptr _ref_direction;    //  OPTIONAL
    public: 
        SdaiAxis2_placement_3d();
        SdaiAxis2_placement_3d( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiAxis2_placement_3d( SdaiAxis2_placement_3d & e );
        ~SdaiAxis2_placement_3d();
        int opcode() {
            return 152;
        }
        SdaiDirection_ptr_c axis_() const;
        SdaiDirection_ptr   axis_();
        void axis_( const SdaiDirection_ptr x );

        SdaiDirection_ptr_c ref_direction_() const;
        SdaiDirection_ptr   ref_direction_();
        void ref_direction_( const SdaiDirection_ptr x );

};

inline SdaiAxis2_placement_3d * create_SdaiAxis2_placement_3d() {
    return new SdaiAxis2_placement_3d;
}

void init_SdaiAxis2_placement_3d(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_axis2_placement_3d;
    extern AttrDescriptor *a_275axis;
    extern AttrDescriptor *a_276ref_direction;
    extern Derived_attribute *a_277Dp;
}

#endif
