#ifndef  ENTITY_SDAICC_DESIGN_CONTRACT_H
#define  ENTITY_SDAICC_DESIGN_CONTRACT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiCc_design_contract : public SdaiContract_assignment {
     protected:
        SdaiContracted_item_agg_ptr _items;          //  of  contracted_item

    public: 
        SdaiCc_design_contract();
        SdaiCc_design_contract( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiCc_design_contract( SdaiCc_design_contract & e );
        ~SdaiCc_design_contract();
        int opcode() {
            return 104;
        }
        SdaiContracted_item_agg_ptr_c items_() const;
        SdaiContracted_item_agg_ptr   items_();
        void items_( const SdaiContracted_item_agg_ptr x );

};

inline SdaiCc_design_contract * create_SdaiCc_design_contract() {
    return new SdaiCc_design_contract;
}

void init_SdaiCc_design_contract(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_cc_design_contract;
    extern AttrDescriptor *a_202items;
}

#endif
