#ifndef  ENTITY_SDAIAXIS1_PLACEMENT_H
#define  ENTITY_SDAIAXIS1_PLACEMENT_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiAxis1_placement : public SdaiPlacement {
     protected:
        SDAI_Application_instance_ptr _axis;    //  OPTIONAL
    public: 
        SdaiAxis1_placement();
        SdaiAxis1_placement( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiAxis1_placement( SdaiAxis1_placement & e );
        ~SdaiAxis1_placement();
        int opcode() {
            return 10;
        }
        SdaiDirection_ptr_c axis_() const;
        SdaiDirection_ptr   axis_();
        void axis_( const SdaiDirection_ptr x );

};

inline SdaiAxis1_placement * create_SdaiAxis1_placement() {
    return new SdaiAxis1_placement;
}

void init_SdaiAxis1_placement(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_axis1_placement;
    extern AttrDescriptor *a_14axis;
    extern Derived_attribute *a_15Dz;
}

#endif
