#ifndef  ENTITY_SDAIDEGENERATE_TOROIDAL_SURFACE_H
#define  ENTITY_SDAIDEGENERATE_TOROIDAL_SURFACE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiDegenerate_toroidal_surface : public SdaiToroidal_surface {
     protected:
        SDAI_BOOLEAN _select_outer;
    public: 
        SdaiDegenerate_toroidal_surface();
        SdaiDegenerate_toroidal_surface( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiDegenerate_toroidal_surface( SdaiDegenerate_toroidal_surface & e );
        ~SdaiDegenerate_toroidal_surface();
        int opcode() {
            return 87;
        }
        Boolean   select_outer_() const;
        void select_outer_( const Boolean x );

};

inline SdaiDegenerate_toroidal_surface * create_SdaiDegenerate_toroidal_surface() {
    return new SdaiDegenerate_toroidal_surface;
}

void init_SdaiDegenerate_toroidal_surface(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_degenerate_toroidal_surface;
    extern AttrDescriptor *a_177select_outer;
}

#endif
