#ifndef  ENTITY_SDAIEDGE_H
#define  ENTITY_SDAIEDGE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiEdge : public SdaiTopological_representation_item {
     protected:
        SDAI_Application_instance_ptr _edge_start;
        SDAI_Application_instance_ptr _edge_end;
    public: 
        SdaiEdge();
        SdaiEdge( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiEdge( SdaiEdge & e );
        ~SdaiEdge();
        int opcode() {
            return 66;
        }
        SdaiVertex_ptr_c edge_start_() const;
        SdaiVertex_ptr   edge_start_();
        void edge_start_( const SdaiVertex_ptr x );

        SdaiVertex_ptr_c edge_end_() const;
        SdaiVertex_ptr   edge_end_();
        void edge_end_( const SdaiVertex_ptr x );

};

inline SdaiEdge * create_SdaiEdge() {
    return new SdaiEdge;
}

void init_SdaiEdge(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_edge;
    extern AttrDescriptor *a_136edge_start;
    extern AttrDescriptor *a_137edge_end;
}

#endif
