#ifndef  ENTITY_SDAICC_DESIGN_SECURITY_CLASSIFICATION_H
#define  ENTITY_SDAICC_DESIGN_SECURITY_CLASSIFICATION_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiCc_design_security_classification : public SdaiSecurity_classification_assignment {
     protected:
        SdaiClassified_item_agg_ptr _items;          //  of  classified_item

    public: 
        SdaiCc_design_security_classification();
        SdaiCc_design_security_classification( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiCc_design_security_classification( SdaiCc_design_security_classification & e );
        ~SdaiCc_design_security_classification();
        int opcode() {
            return 154;
        }
        SdaiClassified_item_agg_ptr_c items_() const;
        SdaiClassified_item_agg_ptr   items_();
        void items_( const SdaiClassified_item_agg_ptr x );

};

inline SdaiCc_design_security_classification * create_SdaiCc_design_security_classification() {
    return new SdaiCc_design_security_classification;
}

void init_SdaiCc_design_security_classification(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_cc_design_security_classification;
    extern AttrDescriptor *a_279items;
}

#endif
