#ifndef  ENTITY_SDAIFOUNDED_ITEM_H
#define  ENTITY_SDAIFOUNDED_ITEM_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiFounded_item : public SDAI_Application_instance {
    protected:
    public: 
        SdaiFounded_item();
        SdaiFounded_item( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiFounded_item( SdaiFounded_item & e );
        ~SdaiFounded_item();
        int opcode() {
            return 4;
        }
};

inline SdaiFounded_item * create_SdaiFounded_item() {
    return new SdaiFounded_item;
}

void init_SdaiFounded_item(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_founded_item;
}

#endif
