#ifndef  ENTITY_SDAIBEZIER_CURVE_H
#define  ENTITY_SDAIBEZIER_CURVE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiBezier_curve : public SdaiB_spline_curve {
     protected:
    public: 
        SdaiBezier_curve();
        SdaiBezier_curve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiBezier_curve( SdaiBezier_curve & e );
        ~SdaiBezier_curve();
        int opcode() {
            return 14;
        }
};

inline SdaiBezier_curve * create_SdaiBezier_curve() {
    return new SdaiBezier_curve;
}

void init_SdaiBezier_curve(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_bezier_curve;
}

#endif
