#ifndef  ENTITY_SDAICONFIGURATION_DESIGN_H
#define  ENTITY_SDAICONFIGURATION_DESIGN_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiConfiguration_design : public SDAI_Application_instance {
    protected:
        SDAI_Application_instance_ptr _configuration;
        SDAI_Application_instance_ptr _design;
    public: 
        SdaiConfiguration_design();
        SdaiConfiguration_design( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiConfiguration_design( SdaiConfiguration_design & e );
        ~SdaiConfiguration_design();
        int opcode() {
            return 120;
        }
        SdaiConfiguration_item_ptr_c configuration_() const;
        SdaiConfiguration_item_ptr   configuration_();
        void configuration_( const SdaiConfiguration_item_ptr x );

        SdaiProduct_definition_formation_ptr_c design_() const;
        SdaiProduct_definition_formation_ptr   design_();
        void design_( const SdaiProduct_definition_formation_ptr x );

};

inline SdaiConfiguration_design * create_SdaiConfiguration_design() {
    return new SdaiConfiguration_design;
}

void init_SdaiConfiguration_design(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_configuration_design;
    extern AttrDescriptor *a_228configuration;
    extern AttrDescriptor *a_229design;
}

#endif
