#ifndef  ENTITY_SDAIPLANE_H
#define  ENTITY_SDAIPLANE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiPlane : public SdaiElementary_surface {
     protected:
    public: 
        SdaiPlane();
        SdaiPlane( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiPlane( SdaiPlane & e );
        ~SdaiPlane();
        int opcode() {
            return 170;
        }
};

inline SdaiPlane * create_SdaiPlane() {
    return new SdaiPlane;
}

void init_SdaiPlane(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_plane;
}

#endif
