#ifndef  ENTITY_SDAISHAPE_REPRESENTATION_RELATIONSHIP_H
#define  ENTITY_SDAISHAPE_REPRESENTATION_RELATIONSHIP_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiShape_representation_relationship : public SdaiRepresentation_relationship {
     protected:
    public: 
        SdaiShape_representation_relationship();
        SdaiShape_representation_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiShape_representation_relationship( SdaiShape_representation_relationship & e );
        ~SdaiShape_representation_relationship();
        int opcode() {
            return 16;
        }
};

inline SdaiShape_representation_relationship * create_SdaiShape_representation_relationship() {
    return new SdaiShape_representation_relationship;
}

void init_SdaiShape_representation_relationship(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_shape_representation_relationship;
}

#endif
