#ifndef  ENTITY_SDAIORDINAL_DATE_H
#define  ENTITY_SDAIORDINAL_DATE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiOrdinal_date : public SdaiDate {
     protected:
        SDAI_Integer _day_component;
    public: 
        SdaiOrdinal_date();
        SdaiOrdinal_date( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiOrdinal_date( SdaiOrdinal_date & e );
        ~SdaiOrdinal_date();
        int opcode() {
            return 182;
        }
        SdaiDay_in_year_number   day_component_() const;
        void day_component_( const SdaiDay_in_year_number x );

};

inline SdaiOrdinal_date * create_SdaiOrdinal_date() {
    return new SdaiOrdinal_date;
}

void init_SdaiOrdinal_date(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_ordinal_date;
    extern AttrDescriptor *a_325day_component;
}

#endif
