#ifndef  ENTITY_SDAIGEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION_H
#define  ENTITY_SDAIGEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiGeometrically_bounded_wireframe_shape_representation : public SdaiShape_representation {
     protected:
    public: 
        SdaiGeometrically_bounded_wireframe_shape_representation();
        SdaiGeometrically_bounded_wireframe_shape_representation( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiGeometrically_bounded_wireframe_shape_representation( SdaiGeometrically_bounded_wireframe_shape_representation & e );
        ~SdaiGeometrically_bounded_wireframe_shape_representation();
        int opcode() {
            return 147;
        }
};

inline SdaiGeometrically_bounded_wireframe_shape_representation * create_SdaiGeometrically_bounded_wireframe_shape_representation() {
    return new SdaiGeometrically_bounded_wireframe_shape_representation;
}

void init_SdaiGeometrically_bounded_wireframe_shape_representation(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_geometrically_bounded_wireframe_shape_representation;
}

#endif
