#ifndef  ENTITY_SDAIVERTEX_LOOP_H
#define  ENTITY_SDAIVERTEX_LOOP_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiVertex_loop : public SdaiLoop {
     protected:
        SDAI_Application_instance_ptr _loop_vertex;
    public: 
        SdaiVertex_loop();
        SdaiVertex_loop( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiVertex_loop( SdaiVertex_loop & e );
        ~SdaiVertex_loop();
        int opcode() {
            return 156;
        }
        SdaiVertex_ptr_c loop_vertex_() const;
        SdaiVertex_ptr   loop_vertex_();
        void loop_vertex_( const SdaiVertex_ptr x );

};

inline SdaiVertex_loop * create_SdaiVertex_loop() {
    return new SdaiVertex_loop;
}

void init_SdaiVertex_loop(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_vertex_loop;
    extern AttrDescriptor *a_282loop_vertex;
}

#endif
