#ifndef  ENTITY_SDAIWEEK_OF_YEAR_AND_DAY_DATE_H
#define  ENTITY_SDAIWEEK_OF_YEAR_AND_DAY_DATE_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiWeek_of_year_and_day_date : public SdaiDate {
     protected:
        SDAI_Integer _week_component;
        SDAI_Integer _day_component;    //  OPTIONAL
    public: 
        SdaiWeek_of_year_and_day_date();
        SdaiWeek_of_year_and_day_date( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiWeek_of_year_and_day_date( SdaiWeek_of_year_and_day_date & e );
        ~SdaiWeek_of_year_and_day_date();
        int opcode() {
            return 107;
        }
        SdaiWeek_in_year_number   week_component_() const;
        void week_component_( const SdaiWeek_in_year_number x );

        SdaiDay_in_week_number   day_component_() const;
        void day_component_( const SdaiDay_in_week_number x );

};

inline SdaiWeek_of_year_and_day_date * create_SdaiWeek_of_year_and_day_date() {
    return new SdaiWeek_of_year_and_day_date;
}

void init_SdaiWeek_of_year_and_day_date(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_week_of_year_and_day_date;
    extern AttrDescriptor *a_209week_component;
    extern AttrDescriptor *a_210day_component;
}

#endif
