#ifndef  ENTITY_SDAIHYPERBOLA_H
#define  ENTITY_SDAIHYPERBOLA_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiHyperbola : public SdaiConic {
     protected:
        SDAI_Real _semi_axis;
        SDAI_Real _semi_imag_axis;
    public: 
        SdaiHyperbola();
        SdaiHyperbola( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiHyperbola( SdaiHyperbola & e );
        ~SdaiHyperbola();
        int opcode() {
            return 85;
        }
        SdaiPositive_length_measure   semi_axis_() const;
        void semi_axis_( const SdaiPositive_length_measure x );

        SdaiPositive_length_measure   semi_imag_axis_() const;
        void semi_imag_axis_( const SdaiPositive_length_measure x );

};

inline SdaiHyperbola * create_SdaiHyperbola() {
    return new SdaiHyperbola;
}

void init_SdaiHyperbola(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_hyperbola;
    extern AttrDescriptor *a_172semi_axis;
    extern AttrDescriptor *a_173semi_imag_axis;
}

#endif
