#ifndef  SCHEMA_H
#define  SCHEMA_H

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


// in the exp2cxx source code, this file is generally referred to as files->incall or schemafile

#ifndef SC_SCHEMA_EXPORT
# if defined(SC_SCHEMA_DLL_EXPORTS) && defined(SC_SCHEMA_DLL_IMPORTS)
#  error "SC_SCHEMA_DLL_EXPORTS or SC_SCHEMA_DLL_IMPORTS can be defined, not both."
# elif defined(SC_SCHEMA_DLL_EXPORTS)
#  define SC_SCHEMA_EXPORT __declspec(dllexport)
# elif defined(SC_SCHEMA_DLL_IMPORTS)
#  define SC_SCHEMA_EXPORT __declspec(dllimport)
# else
#  define SC_SCHEMA_EXPORT
# endif
#endif

#ifdef SC_LOGGING
#include <sys/time.h>
#endif
#include <sdai.h>


#include <Registry.h>

#include <STEPaggregate.h>

#include <STEPundefined.h>

#include <ExpDict.h>

#include <STEPattribute.h>

#include <Sdaiclasses.h>
extern SC_SCHEMA_EXPORT void SchemaInit (Registry &);
extern SC_SCHEMA_EXPORT void InitSchemasAndEnts (Registry &);
#include "SdaiCONFIG_CONTROL_DESIGNNames.h"
#include "SdaiCONFIG_CONTROL_DESIGN.h" 
extern void SdaiCONFIG_CONTROL_DESIGNInit (Registry & r);

#include <complexSupport.h>
ComplexCollect *gencomplex();

SDAI_Model_contents_ptr GetModelContents(char *schemaName);
#endif
