#ifndef  SCHEMA_CC
#define  SCHEMA_CC

// This file was generated by exp2cxx,
// git commit id: 0.8, build timestamp 03 Nov 2020 03:17.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


// in the exp2cxx source code, this file is generally referred to as files->initall or schemainit
#include "schema.h"
#include "sc_memmgr.h"
class Registry;

void SchemaInit (Registry & reg) {
     extern void InitSchemasAndEnts (Registry & r);
     InitSchemasAndEnts (reg);
     extern void SdaiCONFIG_CONTROL_DESIGNInit (Registry & r);
     SdaiCONFIG_CONTROL_DESIGNInit (reg); 
     reg.SetCompCollect( gencomplex() );
}

/*    Generated at /Users/Bruno/OpenVSP-python3/OpenVSP/buildlibs/STEPCODE-prefix/src/STEPCODE/src/exp2cxx/classes_wrapper.cc:580.    */

// Generate a function to be called by Model to help it
// create the necessary Model_contents without the
// dictionary (Registry) handle since it doesn't have a
// predetermined way to access to the handle.

SDAI_Model_contents_ptr GetModelContents(char *schemaName) {
    if(!strcmp(schemaName, "config_control_design"))
        return (SDAI_Model_contents_ptr) new SdaiModel_contents_config_control_design; 
    else return (SDAI_Model_contents_ptr) 0;
}
#endif
